# Stage 1 - Build Angular App
FROM node:18 AS build
WORKDIR /app
COPY . .
RUN npm install
RUN npm run build --prod

# Stage 2 - Serve Angular via NGINX
FROM nginx:alpine
COPY --from=build /app/dist/sarkari-service /usr/share/nginx/html
COPY ../nginx/default.conf /etc/nginx/conf.d/default.conf
